adoptium/openj9-systemtest

build.xml
openj9.build/playlist.xml

Issue 5 : Integrate openj9-systemtest with testkitgen

---

openj9.build/include/top.xml

Fixes https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/127

Use curl to download systemtest prereqs when on zos

---

openj9.build/include/top.xml

Fix description of download-file macro

Fix description of download-file macro

---

openj9.build/include/top.xml

Fixes: eclipse/openj9-systemtest#29

Update <get-platform-arch> macro for ppc64le platform

---

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClasses.java

Fixes https://github.com/eclipse/openj9-systemtest/issues/35

Update validation regex to match change in cache stat output in jdk10

---

.gitattributes.zos
openj9.build/include/top.xml
openj9.stf.extensions/build.xml
openj9.test.daa/build.xml
openj9.test.jlm/build.xml
openj9.test.load/build.xml
openj9.test.sharedClasses.jvmti/build.xml
openj9.test.sharedClasses/build.xml

Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/139 

Enable systemtest on z/OS

---

README.md

Correct git repository path to openj9-systemtest

Correct git repository path to openj9-systemtest

---

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClassesWorkloadTest_Softmx_Increase_JitAot.java

Resolves https://github.com/eclipse/openj9-systemtest/issues/41
Signed-off-by: Mesbah Mesbah_Alam@ca.ibm.com

Update SSC Softmx JITAOT test to remove unnecessary checks

---

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClassesWorkloadTest_Softmx_Increase_JitAot.java
openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/test/sc/SCSoftmxTestUtil.java

Resolves https://github.com/eclipse/openj9-systemtest/issues/43

Accept equal value for aot or jit data after softmx increase

---

openj9.build/build.xml
openj9.build/include/top.xml

Signed-off-by: Simon Rushton <rushton@uk.ibm.com>

Check jvm version using java.vm.version property

---

openj9.build/makefile

Signed-off-by: Simon Rushton <rushton@uk.ibm.com>

Changes to allow execution under cygwin

---

openj9.test.sharedClasses.jvmti/src/native/Makefile

Add white space in lflags
Signed-off-by: Mesbah_Alam@ca.ibm.com

Add white space in lflags

---

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClassesWorkloadTest_Softmx_IncreaseDecrease.java

Fixes https://github.com/eclipse/openj9/issues/4139

Increase softmx intermediate limit to 30 mb

---

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClassesWorkloadTest_Softmx_IncreaseDecrease.java

Calibrate value to which to increase softmx size

Calibrate value to which to increase softmx size

---

openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/stf/SharedClassesAPI.java

Add missing comma in SharedClasses Command

Add missing comma in SharedClasses Command

---

openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/sc/api/SharedClassesCacheChecker.java

Only verify and delete the given test cache

Only verify and delete the given test cache

---

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClassesWorkloadTest_Softmx_Increase.java

Resolves https://github.com/eclipse/openj9-systemtest/issues/92
FYI @hangshao0

Accept 99% soft full cache in SharedClassesWorkloadTest_Softmx_Increase test

---

openj9.test.sharedClasses.jvmti/build.xml

Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/286

Update native build script to explicitly invoke gmake on AIX

---

openj9.test.load/src/test.load/net/openj9/stf/DaaLoadTest.java

Updates DAA load tests to dynamically check if special JIT options (e.g. -Xjit:count=0, etc) are being used in a test and adjust to a lower load if true. This will allow the DAA load tests to run normally with special JIT modes and not time out.
Related to : https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/292 
Related PRs: 
- https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/293
- https://github.com/AdoptOpenJDK/stf/pull/68

Calibrate load level for special modes in DAA load test

---

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClasses.java

Reduce workload on LoaderSlaveMultiThreadMultiCL

---

openj9.test.sharedClasses.jvmti/src/native/Makefile

Resolves https://github.com/eclipse/openj9-systemtest/issues/90 

Add linux_arm-64 to supported platforms for shareccclasses jvmti test

---

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/test/sc/LoaderSlaveMultiJar.java
openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/test/sc/LoaderSlaveMultiThread.java
openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/test/sc/LoaderSlaveMultiThreadMultiCL.java

Related to : https://github.com/eclipse/openj9-systemtest/issues/103

Limit all variants of SharedClasses test to 10 minutes

---

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClasses.java

Related to https://github.com/eclipse/openj9/issues/8972 

Add new debug options for SharedClasses  SCM01 MultiThread test

---

openj9.build/docs/build.md
openj9.test.jlm/.classpath

Updates build paths + documentation for log4j 2.13.3 update
Related to https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/347

Update documentation for log4j 2.13.3 update for stf

---

openj9.test.jlm/src/test.jlm.ibm/net/openj9/test/jlm/TestIBMJlmRemoteClassAuth.java
openj9.test.jlm/src/test.jlm.ibm/net/openj9/test/jlm/TestIBMJlmRemoteClassNoAuth.java
openj9.test.jlm/src/test.jlm.ibm/net/openj9/test/jlm/TestIBMJlmRemoteMemoryAuth.java
openj9.test.jlm/src/test.jlm.ibm/net/openj9/test/jlm/TestIBMJlmRemoteMemoryNoAuth.java

Signed-off-by: Simon Rushton <rushton@uk.ibm.com>

Adjust load parameters to eliminate test timeouts

---

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClasses.java

Add -Xdump option to all SCM01 tests

---

openj9.test.load/src/test.load/net/openj9/stf/DaaLoadTest.java

- The logic of how the tests figure out when slow running JIT modes are in effect has been modified. Now the test will treat any JIT option that contains `-Xjit:count` or `Xjit:enableOSR` (e.g. Mode614, Modew553, etc and the OSR modes) as slow running options and use a reduced workload. This will now ensure we do not run the "regular" (longer) load when any of these JIT modes are in use.
- Related to : https://github.com/eclipse/openj9-systemtest/issues/121

Have a single reduced workload for Daa tests regardless of jit options

---

openj9.test.load/src/test.load/net/openj9/stf/DaaLoadTest.java
openj9.test.load/src/test.load/net/openj9/stf/HeapHogLoadTest.java
openj9.test.load/src/test.load/net/openj9/stf/ObjectTreeLoadTest.java

- Enable time-based load test mechanism in openj9-systemtest load tests  
- Related to https://github.com/AdoptOpenJDK/openjdk-tests/issues/2104

Enable time-based load test mechanism in openj9-systemtest load tests

---

openj9.test.jlm/src/test.jlm.ibm/net/openj9/test/jlm/remote/ClassProfiler.java
openj9.test.jlm/src/test.jlm.ibm/net/openj9/test/jlm/remote/MemoryProfiler.java

Signed-off-by: Simon Rushton <srushton@redhat.com>

Print stack trace for ConnectException and UnmarshalException

---

openj9.build/build.xml
openj9.build/docs/build.md
openj9.build/scripts/openj9-systemtest-clone-make.bat
openj9.build/scripts/openj9-systemtest-clone-make.sh
openj9.test.jlm/build.xml
openj9.test.sharedClasses.jvmti/build.xml
openj9.test.sharedClasses/build.xml

Related to https://github.com/adoptium/aqa-systemtest/issues/424

Replace references of openjdk-systemtest with aqa-systemtest

---

openj9.test.daa/src/test.daa/net/openj9/test/decimals/TestPD2ED.java

Add `@Test` annotation to
`testConvertEmbeddedTrailingNonZeroPackedDecimalOffset`
Singed-off-by: Shubham Verma <shubhamv.sv@gmail.com>

Add `@Test` annotation to pd2ed corner case method
