adoptium/openj9-systemtest

openj9.build/include/top.xml
Running build configure throws a malformed encoding exception
if there is "\u" character appearing in the PATH on Windows.
This fix resolves the issue by changing the single "\" to "\\"
in the generated file.
Fixes: #4
Signed-off-by: sabkrish <sabkrish@in.ibm.com>
=> Fix for Malformed \uxxxx encoding error during make configure

README.md
This is to correct the URL for cloning repositories in openj9-systemtest
README file [skip ci] issue #7
Signed-off-by: Pasam Soujanya <psoujany@in.ibm.com>
=> Correcting URL in openj9-systemtest README

README.md
Corrected the broken URL for "STF Sytem Test Framework" in README.md file.
Fixes #9
Signed-off-by: Bhargavi Mullapudi mubharga@in.ibm.com
=> Fix for broken link in README.md

openj9.build/build.xml, openj9.test.sharedClasses.jvmti/build.xml
=> Add flag to only build openj9-systemtest while impl = openj9 + Disable compilation of sharedClasses.jvmti tests

openj9.build/makefile
Add make targets for openj9 specific jlm system tests
=> Add make targets for openj9 specific jlm system tests

openj9.test.daa/src/test.daa/net/openj9/test/PDMoveShifts/TestShiftsAndConvert.java
Fix a PDMoveShifts right shift test to accept both the and
negative binary coded decimal zeros.
DAA Java code and z hardware accelerated logic can produce both positive and negative zeros (0x0D and 0x0C). The test case should check and accept both types of zeros.
Signed-off-by: Nigel Yu <yunigel@ca.ibm.com>
=> Fix PDMoveShifts testShiftRightUnitcases()

openj9.stf.extensions/src/stf.extensions/net/openj9/stf/sharedClasses/StfSharedClassesExtension.java
Resolves https://github.com/eclipse/openj9/issues/2315
=> Fix regex for checking SSC output - include all possible Java versions

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClassesWorkload.java
Resolves https://github.com/eclipse/openj9-systemtest/issues/33
=> Updated test validation string to match cache stats output of Java 10.

openj9.test.sharedClasses.jvmti/build.xml, openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/stf/SharedClassesAPI.java
Temporarily exclude native sharedClasses tests from running on Windows
=> Temporarily exclude native sharedClasses tests from running on Windows

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClasses.java
The problem with the sharedClasses test right now is
that even though there are 5 JVMs invoked, which means
that some JVMs will load AOT code compiled by a different
JVM, it doesn't fully test the AOT load infrastructure
becuase after the test is completed, the SCC gets
destroyed before the next test runs. This commit addresses
this issue by invoking the test twice; once to primarily
populate the SCC, and a second time to primarily load
from it.
https://github.com/eclipse/openj9/issues/3774
Signed-off-by: Irwin D'Souza <dsouzai@ca.ibm.com>
=> Updated SCC test to be invoked twice

openj9.test.sharedClasses.jvmti/src/native/Makefile
Fixes https://github.com/eclipse/openj9-systemtest/issues/53
Signed-off-by: Mesbah Alam <Mesbah_Alam@ca.ibm.com>
=> Add missing IFLAGS value for osx 

openj9.test.sharedClasses.jvmti/src/native/Makefile
https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/212
=> Fix space after LFLAGS in sharedClasses.jvmti build makefile

openj9.test.load/src/test.load/net/openj9/stf/DaaLoadTest.java, openj9.test.load/src/test.load/net/openj9/stf/HeapHogLoadTest.java, openj9.test.load/src/test.load/net/openj9/stf/ObjectTreeLoadTest.java
Disable core dump generation for openj9 load tests
=> Disable core dump generation for openj9 load tests

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClassesWorkloadTest_Softmx_IncreaseDecrease.java
Reduce cache to 1/4th its size so cache is 100% full at final stage
=> Reduce cache to 1/4th its size so cache is 100% full at final stage

openj9.stf.extensions/src/stf.extensions/net/openj9/stf/sharedClasses/StfSharedClassesExtension.java, openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/stf/SharedClassesAPI.java, openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClasses.java, openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClassesWorkload.java, openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClassesWorkloadTest_Softmx_Increase.java, openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClassesWorkloadTest_Softmx_IncreaseDecrease.java, openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClassesWorkloadTest_Softmx_Increase_JitAot.java, openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/test/sc/SCSoftmxTestUtil.java
Only destroy test specific caches at setup and teardown of tests
=> Only destroy test specific caches at setup and teardown of SCC tests

openj9.stf.extensions/src/stf.extensions/net/openj9/stf/sharedClasses/StfSharedClassesExtension.java, openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/sc/api/SharedClassesCacheChecker.java, openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/stf/SharedClassesAPI.java
Fixes https://github.com/eclipse/openj9-systemtest/issues/73
=> Update SharedClassesCacheChecker to only delete test-specific cache

openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/sc/api/SharedClassesCacheChecker.java, openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/stf/SharedClassesAPI.java
Run SharedClassesCacheChecker with only workload caches
Fixes: https://github.com/eclipse/openj9-systemtest/issues/78
=> Manage workload caches

openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/stf/SharedClassesAPI.java
=> Use shorter path for cacheDir since on Windows MAX_PATH is 260

openj9.build/include/top.xml, openj9.test.sharedClasses.jvmti/src/native/Makefile
Resolves: https://github.com/eclipse/openj9-systemtest/issues/84
=> Add aarch32 & aarch64 to list of supported archs in openj9-systemtest build script

openj9.test.daa/src/test.daa/net/openj9/test/PDMoveShifts/TestShiftsAndConvert.java
Two packed decimal test functions are invoking packed decimal shift API
with checkOverflow parameter set to false. Ignore-overflow-mode allows the hardware-accelerated 
PD shift operations to completely finish and produce hardware preferred positive zeros.
Fix two test functions so they accept both positive and negative zeros.
Signed-off-by: Nigel Yu <yunigel@ca.ibm.com>
=> Fix packed decimal test cases to expect positive zero

openj9.test.daa/src/test.daa/net/openj9/test/PDMoveShifts/TestShiftsAndConvert.java
Make testZeroShifts2 test case expect both positive and negative zeros
Signed-off-by: Nigel Yu <yunigel@ca.ibm.com>
=> Fix testZeroShifts2 to expect both positive and negative zeros

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClasses.java
Increase timeout of the test as it fails by timing out occasionally on mac
Related to : https://github.com/eclipse/openj9/issues/6765#issuecomment-522597117
=> Increase timeout value as the test fails by timing out on mac

openj9.test.load/src/test.load/net/openj9/stf/DaaLoadTest.java
- Related to : https://github.com/eclipse/openj9-systemtest/issues/95
- Use reduced workload when following special mode is used: `-Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation`
=> Use reduced load for -Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation

openj9.test.load/src/test.load/net/openj9/stf/DaaLoadTest.java
Related to https://github.com/eclipse/openj9-systemtest/issues/95#issuecomment-536212996
=> Treat -Xjit:count=0,optlevel=warm,gcOnResolve,rtResolve as slow arg

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClasses.java, openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/test/sc/LoaderSlaveMultiCL.java
Issue: https://github.com/eclipse/openj9/issues/7178
=> Reduce load in MultiCL SharedClasses test  

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClassesWorkloadTest_Softmx_IncreaseDecrease.java, openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/test/sc/SCSoftmxTestUtil.java
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/324
=> Remove use of deprecated modules in sc up-down test

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClasses.java, openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/test/sc/LoaderSlaveMultiThread.java
- Print ps v <pid> debug message for linux and aix in LoaderSlaveMultiThread
- Related to https://github.com/eclipse/openj9/issues/8842
=> Print ps v <pid> debug message for linux and aix in LoaderSlaveMultiThread

openj9.test.sharedClasses.jvmti/src/native/Makefile
Add compiler flags and options for linux ppc 32 bit platform to shared classes native build script
Resolves https://github.ibm.com/runtimes/backlog/issues/308
Signed-off-by: Mesbah_Alam@ca.ibm.com Mesbah_Alam@ca.ibm.com
=> Add compiler options for linux ppc 32 bit platform to shared classes native build script

openj9.test.sharedClasses.jvmti/src/native/Makefile
Add linux_390-32 and zos_390-32 to the list of supported platforms in test build script.
Background: backlog/issues/307
FYI @lumpfish 
=> Add zos_390-32 and linux_390-32 to list of supported PLATFORM

openj9.test.load/src/test.load/net/openj9/stf/DaaLoadTest.java
This PR reduces workload of DAA load tests and sets a reasonable timeout value for each sub-test. The previous workloads were too much and at times was taking [too long](https://github.com/eclipse/openj9-systemtest/issues/121) for the test to finish. 
Resolves https://github.com/eclipse/openj9-systemtest/issues/121
@pshipton
=> Set reasonable timeout valeus for Daa load test variants

openj9.test.daa/.classpath, openj9.test.jlm/.classpath, openj9.test.load/.classpath, openj9.test.sharedClasses.jvmti/.classpath, openj9.test.sharedClasses/.classpath
- Removes version number from all prereq jar references in openj9-systemtest repo
- Related to : https://github.com/AdoptOpenJDK/stf/issues/98
=> Remove hard-coded version numbers from prereq jar references

openj9.build/makefile
- Adds time-based test targets to openj9-systemtest make layer
- Removes Ant version numbers from openjdk.systemtest make layer (missed by https://github.com/AdoptOpenJDK/stf/issues/98)
- Related PR https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/409
- Related issue https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/407
=> Add time-based test targets to openj9-systemtest make layer

openj9.test.sharedClasses.jvmti/build.xml, openj9.test.sharedClasses.jvmti/src/native/Makefile, openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/stf/SharedClassesAPI.java
- Remove dependency of openj9-systemtest native makefiles on PLATFORM variable 
- Use uname commands to figure out platforms and platforms specific compiler settings 
- Reduce unnecessary platform-specific compiler flags
Related to : https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/413
=> Cleanup native systemtest makefile

README.md, openj9.build/docs/build.md, openj9.build/scripts/openj9-systemtest-clone-make.bat, openj9.build/scripts/openj9-systemtest-clone-make.sh, openj9.stf.extensions/src/stf.extensions/net/openj9/stf/sharedClasses/StfSharedClassesExtension.java, openj9.test.sharedClasses.jvmti/build.xml, openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/sc/api/SharedClassesCacheChecker.java, openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/stf/SharedClassesAPI.java, openj9.test.sharedClasses/docs/README.md
Fixes https://github.com/adoptium/aqa-tests/issues/2551
=> Updated github URLS from eclipse to eclipse-openj9

openj9.test.daa/src/test.daa/net/openj9/test/decimals/TestPD2ED.java
Packed decimal to external decimal conversion corner cases:
- Max precision for preferred and alternate sign
- Non 0 packed decimal offset
- ending at the sign byte
- ending at non sign byte
Signed-off-by:Shubham Verma <shubhamv.sv@gmail.com>
=> Add ED sign embedded trailing corner cases

openj9.test.sharedClasses.jvmti/src/native/Makefile
- Add required flags to specify bitmode for compile and link commands for openj9.test.sharedClasses.jvmti 
- Related to : openj9-openjdk-jdk11-zos/issues/738
FYi @pshipton 
Signed-off-by: Mesbah-Alam <Mesbah_Alam@ca.ibm.com>
=> Add required flags to specify bitmode for compile and link commands for openj9.test.sharedClasses.jvmti 

openj9.test.daa/src/test.daa/net/openj9/test/decimals/TestPD2ED.java
Test method `testConvertEmbeddedTrailingNonZeroPackedDecimalOffset`
shouldn't be static.
Signed-off-by: Shubham Verma <shubhamv.sv@gmail.com>
=> Remove static keyword from pd2zd test method

openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/stf/SharedClassesAPI.java
This commit excludes JVMTI tests in SharedClassesAPI on AArch64 macOS
for the time being, because JVMTI support is not fully working yet on
that platform.
Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>
=> AArch64 macOS: Exclude JVMTI tests in SharedClassesAPI

openj9.test.daa/src/test.daa/net/openj9/test/PDMoveShifts/TestShiftsAndConvert.java
Signed-off-by: Shubham Verma <shubhamv.sv@gmail.com>
=> Add resoning behind comparison to -0 and +0

openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/stf/SharedClassesAPI.java
This commit reverts the change in #141, to enable JVMTI tests in
SharedClassesAPI on AArch64 macOS back again.
Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>
=> AArch64 macOS: Enable JVMTI tests in SharedClassesAPI

openj9.test.jlm/src/test.jlm.ibm/net/openj9/test/extensions/OperatingSystemExtensionCommand.java, openj9.test.jlm/src/test.jlm.ibm/net/openj9/test/management/TestOperatingSystemMXBean_Local.java, openj9.test.jlm/src/test.jlm.ibm/net/openj9/test/management/TestOperatingSystemMXBean_Remote.java
Otherwise the test code does not compile on jdk19 where the methods are
removed.
See https://github.com/eclipse-openj9/openj9/pull/15127
See the compile problems in build https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK19/68/
Tested in grinder https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/833
=> Replace jdk8 OpenJ9 deprecated methods with equivalents

CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md
The code of conduct and security files are copied from the OpenJ9 repo. The contributing file is a stub that refers to the OpenJ9 repo.
=> Add code of conduct, contributing, security files

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClasses.java
- adds the classes.jar file contained in the SharedClassesTestdata to the sharedClassesTestData/v1/jdkversion directory
related:eclipse-openj9/openj9#19582
Signed-off-by: Anna Babu Palathingal <anna.bp@ibm.com>
=> Add classes.jar for sharedClassesTestData into specific jdk version dir.

openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/stf/SharedClassesAPI.java
Should fix failure seen in https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_aarch64_mac_Release/86.
=> Correct shared library suffix on macOS

openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/stf/SharedClassesAPI.java
Reverts adoptium/openj9-systemtest#158
=> Revert "Correct shared library suffix on macOS"

openj9.test.sharedClasses.jvmti/build.xml, openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/stf/SharedClassesAPI.java
This reverts commit ef15ae73e9b6a98e57a210dfd50ece8d48f0c79f.
Closes: https://github.com/adoptium/openj9-systemtest/issues/157
=> Revert "Temporarily exclude native sharedClasses tests on Windows"

openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClasses.java
- ensure the presence of classes.jar , if doesnt exist regenerate it.
resolves: https://github.com/eclipse-openj9/openj9/issues/19582
=> Handle missing classes.jar in sharedClassesTestData
